name: Build and upload test suite

on:
  workflow_dispatch:
  push:
    branches:
    - main
    
#concurrency:
#  group: test-build-${{ github.event.pull_request.number || github.ref_name }}
#  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  fetch_release:
    runs-on: ubuntu-latest
    outputs: 
      releases: ${{ steps.fetch_release.outputs.releases }}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/CleverRaven/Cataclysm-DDA/releases?per_page=2 > data.json
          matrix=$(jq '[.[]|.tag_name]' data.json | sed 's/[[:space:]]//g' | sed 's/"//g')
          echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
          echo $matrix
          echo "$matrix" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_ENV
  matrix_build:
    needs: [fetch_release]
    strategy:
      fail-fast: false
      matrix: 
        release: ${{ fromJson(needs.fetch_release.outputs.releases) }}
    runs-on: ubuntu-latest
    name: ${{ matrix.release }}
    env:
      ZSTD_CLEVEL: 17
      COMPILER: clang++-10
      TILES: 0
      SOUND: 0
      LOCALIZE: 1
      MODS: --mods=magiclysm
      EXTRA_TEST_OPTS: --error-format=github-action
      PCH: 1
      RELEASE: 1
      ARCHIVE_SUCCESS: basic-build
      CCACHE_LIMIT: 2G
      CCACHE_FILECLONE: true
      CCACHE_HARDLINK: true
      CCACHE_NOCOMPRESS: true
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        repository: 'CleverRaven/Cataclysm-DDA'
        ref: ${{ matrix.release }}
      
