name: Build and upload test suite

on:
  workflow_dispatch:
  push:
    branches:
    - main
    
#concurrency:
#  group: test-build-${{ github.event.pull_request.number || github.ref_name }}
#  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/CleverRaven/Cataclysm-DDA/releases?per_page=1 > data.json
          jq '.["tag_name"] | []' data.json
