name: Generate download link

on:
  workflow_dispatch:
  schedule:
    - cron: '40 18 * * *'
jobs:
  fetch_release:
    runs-on: ubuntu-latest
    outputs: 
      releases: ${{ steps.fetch.outputs.releases }}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: fetch
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/CleverRaven/Cataclysm-DDA/releases?per_page=1 > data.json
          matrix=$(
            echo '{ "release" : '
            (jq '[.[]|.tag_name]' data.json | sed 's/[[:space:]]//g')
            echo '}'
              )
          matrix=$(echo $matrix | sed ':a;N;$!ba;s/\n/;/g') 
          matrix1="{ \"release\" : [ \"cdda-experimental-2023-07-23-0530\", \"cdda-experimental-2023-07-22-2222\" ] }"
          echo $matrix1
          echo $matrix
          echo "releases=$matrix" >> $GITHUB_OUTPUT
  matrix_build:
    needs: [ fetch_release ]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.fetch_release.outputs.releases) }}
    runs-on: ubuntu-latest
    name: ${{ matrix.release }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: result
        fetch-depth: 0
    - name: Commit files
      run: |
          sudo apt-get update
          sudo apt-get install curl
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          release=${{ matrix.release }}
          release=${release#*-}
          release=${release#*-}
          link_prefix="mirror.ghproxy.com/github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-"$release"/"

          msvc_link=""$link_prefix"cdda-windows-tiles-x64-msvc-"$release".zip"
          mingw_link=""$link_prefix"cdda-windows-tiles-x64-"$release".zip"
          android_link=""$link_prefix"cdda-android-x64-"$release".apk"
          
          curl -L -o temp $msvc_link
          if [ $(ls -l temp | awk '{print $5}') -lt 100 ]; then
            msvc_link="无"
          fi
          curl -L -o temp $mingw_link
          if [ $(ls -l temp | awk '{print $5}') -lt 100 ]; then
            mingw_link="无"
          fi
          curl -L -o temp $android_link
          if [ $(ls -l temp | awk '{print $5}') -lt 100 ]; then
            android_link=="无"
          fi
          rm -f temp
          echo -e $release"\n" > README.md
          echo -e "Android x64:\n" >> README.md
          echo -e ""$android_link"\n" >> README.md
          echo -e "Windows x64 msvc:\n" >> README.md
          echo -e ""$msvc_link"\n" >> README.md
          echo -e "Windows x64:\n" >> README.md
          echo -e ""$mingw_link"\n" >> README.md
          echo -e "请复制链接到浏览器打开\n" >> README.md
          git add .
          git commit -m "auto-update"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: result
        github_token: ${{ secrets.PAT }}
