name: Build and upload test suite

on:
  # 允许手动触发
  workflow_dispatch:
  # 每天定时运行两次（UTC时间 6:40 和 18:40）
  schedule:
    - cron: '40 6,18 * * *'

jobs:
  # --- 第一个 Job: 获取最新的官方 Release 标签 ---
  fetch_release:
    runs-on: ubuntu-latest
    outputs:
      # 将结果输出，供下一个 Job 使用
      releases: ${{ steps.fetch.outputs.releases }}
    steps:
      - name: Fetch latest CDDA release tag and format matrix
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: fetch
        run: |
          # 1. 使用 GitHub API 获取 CleverRaven/Cataclysm-DDA 最新的一个 release
          gh api /repos/CleverRaven/Cataclysm-DDA/releases?per_page=1 > data.json
          
          # 2. 使用 jq -c 一步到位地生成最终的、单行的、完整的 JSON 字符串
          matrix_string=$(jq -c '{ "release": [.[] | .tag_name] }' data.json)
          
          # 3. 打印出来，方便在日志中调试
          echo "Generated Matrix String: $matrix_string"
          
          # 4. 将这个完美的 JSON 字符串写入 GITHUB_OUTPUT
          echo "releases=$matrix_string" >> $GITHUB_OUTPUT

  # --- 第二个 Job: 根据获取到的标签，构建并上传测试程序 ---
  matrix_build:
    # 依赖 fetch_release job 完成
    needs: [ fetch_release ]
    strategy:
      fail-fast: false
      # 从上一个 job 的输出中读取 matrix 配置
      matrix: ${{ fromJSON(needs.fetch_release.outputs.releases) }}
    
    runs-on: ubuntu-latest
    name: Build for ${{ matrix.release }} # Job 的显示名称
    
    # 允许此 Job 写入内容（比如创建 Release）
    permissions:
      contents: write
      
    env:
      COMPILER: clang++-13 # 指定使用 Clang 13
      TILES: 0
      SOUND: 0
      LOCALIZE: 0
      PCH: 1
      RELEASE: 1
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: 1. Create Release Placeholder
      run: |
        # 提前在当前仓库创建一个空的 Release，用于之后上传附件
        # 如果 Release 已存在，此命令会失败但不会中断工作流，这是预期的行为
        gh release create ${{ matrix.release }} --title "Test Suite for ${{ matrix.release }}" --notes "Automated build of the test suite for this version." || echo "Release for tag ${{ matrix.release }} already exists, continuing."
        
    - name: 2. Checkout CDDA Source Code
      # 拉取与 matrix.release 标签版本完全对应的官方 CDDA 源码
      uses: actions/checkout@v4
      with:
        repository: 'CleverRaven/Cataclysm-DDA'
        ref: ${{ matrix.release }}

    - name: 3. Install Build Dependencies
      run: |
        sudo apt-get update
        # 核心修复：在这里安装 clang-13 和 patch
        sudo apt-get install -y clang-13 libncursesw5-dev ccache gettext parallel patch
        sudo locale-gen en_US.UTF-8 de_DE.UTF-8

    - name: 4. Apply Patches
      run: |
        # 克隆包含补丁文件的仓库到临时目录
        git clone https://github.com/SurFlurer/dda-mod-ci.git modci_repo --depth=1
        
        # 应用补丁来创建一个“宽容版”的源码
        # 使用 git apply 命令，它只修改文件而不创建 commit
        git apply modci_repo/patch/0001-disable-test-mode.patch
        git apply modci_repo/patch/0004-no-check-mattack-overwrite.patch

    - name: 5. Prepare for Build
      run: bash ./build-scripts/requirements.sh

    - name: 6. Build the Test Suite
      # 运行编译脚本，生成 cata_test 程序
      run: bash ./build-scripts/gha_compile_only.sh

    - name: 7. Upload Test Suite to Release
      # 上传编译好的 cata_test 文件到之前创建的 Release
      # --clobber 参数表示如果文件已存在，就覆盖它
      run: |
        gh release upload ${{ matrix.release }} tests/cata_test --clobber
