name: grep test results

on:
  workflow_dispatch:
  
jobs:
  fetch-logs:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: fetch
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/SurFlurer/dda-mod-ci/actions/workflows/full-load.yml/runs > run.data
          run_id=$(jq '.workflow_runs|.[0]|.id' run.data)
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/SurFlurer/dda-mod-ci/actions/runs/$run_id/jobs > job.data
          job_id=$(jq '.jobs|.[1]|.id' job.data)
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/SurFlurer/dda-mod-ci/actions/jobs/$job_id/logs | grep "(dda" > logs.data
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/SurFlurer/dda-mod-ci/actions/runs/$run_id/artifacts > arti.data
          arti_url=$(jq '.artifacts|.[0]|.url' arti.data)
          echo $arti_url
          
